import type { Game, Sponsor, Bid, DashboardStats, Placement } from "@/packages/types";

export const mockGames: Game[] = [
  {
    id: "g1",
    title: "Deadzone Chronicles",
    genre: "Zombie Survival",
    artStyle: "Post-Apocalyptic Realism",
    monthlyPlayers: 847_000,
    estimatedRevenue: 42_800,
    status: "live",
    thumbnail: "/demo/deadzone.jpg",
    uploadedAt: "2025-05-01",
    placements: [
      {
        id: "p1",
        gameElement: "Vending Machine — Level 2 Hub",
        location: "Central Safe House",
        suggestedSponsor: "Red Bull",
        brandMatchScore: 94,
        revenuePotential: 12_400,
        status: "approved",
        aiReasoning:
          "High-adrenaline genre strongly correlates with Red Bull's 18–34 male demographic. Asset already rendered in weathered metal matching game's art style.",
        beforeImage: "/demo/before-vending.jpg",
        afterImage: "/demo/after-redbull.jpg",
        createdAt: "2025-05-03",
      },
      {
        id: "p2",
        gameElement: "Rooftop Billboard — Sector 7",
        location: "Abandoned Downtown",
        suggestedSponsor: "Razer",
        brandMatchScore: 88,
        revenuePotential: 8_200,
        status: "pending",
        aiReasoning:
          "Razer's gaming-native audience maps perfectly. Billboard placement is high-visibility — estimated 82% of sessions pass through this sector.",
        beforeImage: "/demo/before-billboard.jpg",
        afterImage: "/demo/after-razer.jpg",
        createdAt: "2025-05-04",
      },
      {
        id: "p3",
        gameElement: "Abandoned Restaurant Facade",
        location: "Main Street — Act 1",
        suggestedSponsor: "Burger King",
        brandMatchScore: 79,
        revenuePotential: 6_100,
        status: "pending",
        aiReasoning:
          "Fast food brands perform well in urban decay environments — ironic juxtaposition drives memorability and brand recall.",
        beforeImage: "/demo/before-restaurant.jpg",
        afterImage: "/demo/after-bk.jpg",
        createdAt: "2025-05-05",
      },
      {
        id: "p4",
        gameElement: "Military Vehicle Wrap — Chapter 3",
        location: "Highway Escape Sequence",
        suggestedSponsor: "Monster Energy",
        brandMatchScore: 91,
        revenuePotential: 9_700,
        status: "denied",
        aiReasoning:
          "Vehicle ads in action sequences receive 3.2x average engagement vs. static placements. Monster's demographic overlap is 87%.",
        createdAt: "2025-05-05",
      },
      {
        id: "p5",
        gameElement: "Loading Screen Interstitial",
        location: "Global",
        suggestedSponsor: "NVIDIA",
        brandMatchScore: 96,
        revenuePotential: 15_600,
        status: "live",
        aiReasoning:
          "NVIDIA's GeForce NOW campaign targets high-end PC gamers. Your player hardware profile shows 68% GPU enthusiasts — exceptional fit.",
        createdAt: "2025-04-28",
      },
    ],
  },
  {
    id: "g2",
    title: "Neon Drift: Tokyo",
    genre: "Street Racing",
    artStyle: "Cyberpunk Neon",
    monthlyPlayers: 1_240_000,
    estimatedRevenue: 78_400,
    status: "live",
    thumbnail: "/demo/neon-drift.jpg",
    uploadedAt: "2025-04-15",
    placements: [
      {
        id: "p6",
        gameElement: "Garage Sponsor Banner",
        location: "Main Pit Area",
        suggestedSponsor: "Castrol",
        brandMatchScore: 97,
        revenuePotential: 22_000,
        status: "live",
        aiReasoning:
          "Automotive product in automotive game. Perfect contextual fit. Castrol's brand colors integrate seamlessly with the game's neon palette.",
        createdAt: "2025-04-18",
      },
      {
        id: "p7",
        gameElement: "Storefront Holo-Signs",
        location: "Shibuya District",
        suggestedSponsor: "Sony",
        brandMatchScore: 85,
        revenuePotential: 14_300,
        status: "pending",
        aiReasoning:
          "Sony's PlayStation branding fits the Japanese aesthetic naturally. High foot traffic area — 94% session exposure rate.",
        createdAt: "2025-04-20",
      },
    ],
  },
  {
    id: "g3",
    title: "Verdant Realm",
    genre: "Fantasy RPG",
    artStyle: "Painterly High Fantasy",
    monthlyPlayers: 560_000,
    estimatedRevenue: 28_100,
    status: "scanning",
    thumbnail: "/demo/verdant.jpg",
    uploadedAt: "2025-05-08",
    placements: [],
  },
];

export const mockSponsors: Sponsor[] = [
  {
    id: "s1",
    name: "Red Bull",
    industry: "Energy Drinks",
    targetAudience: ["18-34 Male", "Extreme Sports", "Gaming"],
    monthlyBudget: 500_000,
    activeBids: 12,
    totalImpressions: 48_200_000,
    brandSafetyScore: 92,
  },
  {
    id: "s2",
    name: "Razer",
    industry: "Gaming Peripherals",
    targetAudience: ["16-30", "PC Gamers", "Esports"],
    monthlyBudget: 350_000,
    activeBids: 8,
    totalImpressions: 31_500_000,
    brandSafetyScore: 98,
  },
  {
    id: "s3",
    name: "NVIDIA",
    industry: "Technology",
    targetAudience: ["18-40", "Tech Enthusiasts", "Gamers"],
    monthlyBudget: 1_200_000,
    activeBids: 24,
    totalImpressions: 92_000_000,
    brandSafetyScore: 99,
  },
  {
    id: "s4",
    name: "Burger King",
    industry: "Fast Food",
    targetAudience: ["16-35", "Casual Gamers", "Urban"],
    monthlyBudget: 220_000,
    activeBids: 5,
    totalImpressions: 18_700_000,
    brandSafetyScore: 85,
  },
];

export const mockBids: Bid[] = [
  {
    id: "b1",
    sponsorId: "s1",
    sponsorName: "Red Bull",
    gameId: "g1",
    gameName: "Deadzone Chronicles",
    placementId: "p1",
    amount: 12_400,
    status: "accepted",
    placedAt: "2025-05-03T14:22:00Z",
  },
  {
    id: "b2",
    sponsorId: "s4",
    sponsorName: "Burger King",
    gameId: "g1",
    gameName: "Deadzone Chronicles",
    placementId: "p3",
    amount: 6_100,
    status: "pending",
    placedAt: "2025-05-05T09:15:00Z",
  },
  {
    id: "b3",
    sponsorId: "s2",
    sponsorName: "Razer",
    gameId: "g1",
    gameName: "Deadzone Chronicles",
    placementId: "p2",
    amount: 8_200,
    status: "pending",
    placedAt: "2025-05-04T16:47:00Z",
  },
  {
    id: "b4",
    sponsorId: "s1",
    sponsorName: "Red Bull",
    gameId: "g2",
    gameName: "Neon Drift: Tokyo",
    placementId: "p7",
    amount: 9_800,
    status: "pending",
    placedAt: "2025-05-06T11:30:00Z",
  },
];

export const mockStats: DashboardStats = {
  developer: {
    estimatedMonthlyRevenue: 149_700,
    pendingBids: 3,
    activePlacements: 8,
    totalGames: 3,
  },
  sponsor: {
    totalImpressions: 92_400_000,
    activeIntegrations: 14,
    audienceDemographicMatch: 87,
    activeBids: 24,
  },
};

export const aiScanSteps = [
  { step: "Parsing scene graph", detail: "Reading Unity scene files and asset manifests", status: "done" as const },
  { step: "Identifying anchor points", detail: "Detecting flat surfaces, meshes & UV-mappable geometry", status: "done" as const },
  { step: "Analyzing scene lighting", detail: "Extracting ambient light temperature and shadow direction", status: "active" as const },
  { step: "Matching brand safety parameters", detail: "Cross-referencing placement context with sponsor guidelines", status: "pending" as const },
  { step: "Generating mockups", detail: "Rendering brand assets via Cloudinary transformation pipeline", status: "pending" as const },
  { step: "Scoring revenue potential", detail: "Calculating CPM based on session heatmaps and player density", status: "pending" as const },
];
